### ISSUE TITLE
How to deploy without changing passcode

### ISSUE THREAD

**Issue by Cactice** [twilio-labs/plugin-rtc#102]
If I don't want to change the passcode when deploying, how can I do that?
For example, can I set the passcode to my specified numbers?

I'm assuming this is not possible as of now.

I'm thinking about making changes in a fork so if there's any advice I'd appreciate it.

**Comment by olipyskoty** [comment]
Hi @Cactice, thanks for reaching out!

Are you trying to update the passcode for the Twilio Video React app? If so, please check out this past [Github issue](https://github.com/twilio/twilio-video-app-react/issues/645) that was submitted to that repository for more information.

If you are referring to the plugin-rtc passcode, we generate the passcode [here](https://github.com/twilio-labs/plugin-rtc/blob/c836f98ad441c2a5f2dfd0edfaa284df4ef72453/src/helpers.js#L15), which we do not plan on changing any time soon. We added the passcode feature for security purposes. Without it, anyone can use your video app and incur charges on your Twilio account. Also, this plugin is only meant to be used for demo purposes, not production. Therefore, instead of hardcoding your app's password, it might be better to add your own authentication to your application, and then deploy it to a production server of your choice (Firebase, Heroku, AWS, etc.).

Hope that helps! Thank you!
