### ISSUE TITLE
How to enable CORS headers

### ISSUE THREAD

**Issue by QasimQureshi** [twilio-labs/plugin-rtc#23]
I'm trying to use Twilio video on my JAMstack site hosted on Netlify.

Is there a way for me to enable cross-origin headers on the /token endpoint, so I can access it externally?

**Comment by timmydoza** [comment]
Hi @QasimQureshi!

Yes - it is possible to add CORS headers to the `/token` endpoint. In order to do this, you'll have to clone this repo and manually edit some files. Try this:

- Clone this repo. `git clone https://github.com/twilio-labs/plugin-rtc.git`
- Run `cd plugin-rtc`
- Run `npm install` to install all dependencies
- Run `twilio plugins:uninstall @twilio-labs/plugin-rtc` to uninstall the version of the plugin that may have been previously installed via NPM. 
- Run `twilio plugins:link .`. This will 'install' the local version of the plugin. 

Then you'll have to add the CORS headers. Add these lines after line 23 of `src/video-token-server.js`. Be sure to update the value of the `Access-Control-Allow-Origin` 

```
  response.appendHeader('Access-Control-Allow-Origin', 'YOUR-DOMAIN.TLD'); // update to match the domain you will make the request from
  response.appendHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
```

Now, when the token serverless function is deployed, it should have cors enabled. 

Good luck - and please let me know if you have any further questions!
