### ISSUE TITLE
Is it possible to deploy without authentication? 

### ISSUE THREAD

**Issue by RusseII** [twilio-labs/plugin-rtc#25]
For example: 
`twilio rtc:apps:video:deploy --authentication none`

**Comment by timmydoza** [comment]
Hey @RusseII!

It isn't possible to deploy without authentication. With no authentication, the app would be open to the world and people could rack up charges to your Twilio account. This feature is not included in this plugin due to the risk.

However, it's possible to clone this repo and edit the code as you see fit. See the README for instructions on how to run a local version of this CLI plugin: https://github.com/twilio-labs/plugin-rtc#install-the-plugin-for-local-development
